### ISSUE TITLE
Pl3xMap tries to save files with invalid filename characters on Windows

### ISSUE THREAD

**Issue by pop4959** [BillyGalbreath/Pl3xMap#122]
Obviously not an issue on Linux, but I was trying to run a quick test of Pl3xMap on Windows and ran into this.

The most obvious solution would be to avoid using `:` in file names entirely, since that would be more portable. Perhaps handle it similarly to how Mojang does with saving dimensions by their namespaced id (create subdirectories), or just replacing it with a valid character.

```
[01:35:02 INFO]: [Pl3xMap] Enabling Pl3xMap v1.19.2-269
[01:35:03 INFO]: [Pl3xMap] Internal webserver running on 0.0.0.0:8080
[01:35:03 ERROR]: Error occurred while enabling Pl3xMap v1.19.2-269 (Is it up to date?)
java.lang.IllegalStateException: Failed to save image 'pl3xmap:spawn'
        at net.pl3x.map.image.IconRegistry.register(IconRegistry.java:65) ~[Pl3xMap-1.19.2-269.jar:?]
        at net.pl3x.map.markers.layer.SpawnLayer.<init>(SpawnLayer.java:39) ~[Pl3xMap-1.19.2-269.jar:?]
        at net.pl3x.map.world.World.init(World.java:174) ~[Pl3xMap-1.19.2-269.jar:?]
        at net.pl3x.map.world.WorldRegistry.register(WorldRegistry.java:23) ~[Pl3xMap-1.19.2-269.jar:?]
        at net.pl3x.map.world.BukkitWorldRegistry.register(BukkitWorldRegistry.java:17) ~[Pl3xMap-1.19.2-269.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at net.pl3x.map.PaperPl3xMap.enable(PaperPl3xMap.java:166) ~[Pl3xMap-1.19.2-269.jar:?]
        at net.pl3x.map.PaperPl3xMap.onEnable(PaperPl3xMap.java:143) ~[Pl3xMap-1.19.2-269.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-142]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-142]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 7: pl3xmap:spawn.png
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
        at java.nio.file.Path.resolve(Path.java:515) ~[?:?]
        at net.pl3x.map.image.IconRegistry.register(IconRegistry.java:62) ~[Pl3xMap-1.19.2-269.jar:?]
        ... 18 more
[01:35:03 INFO]: [Pl3xMap] Disabling Pl3xMap v1.19.2-269
[01:35:03 ERROR]: Error occurred while disabling Pl3xMap v1.19.2-269 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ScheduledFuture.cancel(boolean)" because "this.markersUpdater" is null
        at net.pl3x.map.world.World.stopMarkersTask(World.java:380) ~[Pl3xMap-1.19.2-269.jar:?]
        at net.pl3x.map.world.World.unload(World.java:437) ~[Pl3xMap-1.19.2-269.jar:?]
        at net.pl3x.map.world.WorldRegistry.unregister(WorldRegistry.java:53) ~[Pl3xMap-1.19.2-269.jar:?]
        at net.pl3x.map.world.WorldRegistry.unregister(WorldRegistry.java:12) ~[Pl3xMap-1.19.2-269.jar:?]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at net.pl3x.map.registry.Registry.unregister(Registry.java:76) ~[Pl3xMap-1.19.2-269.jar:?]
        at net.pl3x.map.PaperPl3xMap.disable(PaperPl3xMap.java:204) ~[Pl3xMap-1.19.2-269.jar:?]
        at net.pl3x.map.PaperPl3xMap.onDisable(PaperPl3xMap.java:148) ~[Pl3xMap-1.19.2-269.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-142]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-142]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:35:03 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.pl3x.map.cloud.commandframework.CommandTree$Node.getValue()" because the return value of "net.pl3x.map.cloud.commandframework.bukkit.BukkitCommand.namedNode()" is null
        at net.pl3x.map.cloud.commandframework.bukkit.BukkitCommand.getUsage(BukkitCommand.java:200) ~[Pl3xMap-1.19.2-269.jar:?]
        at org.bukkit.help.GenericCommandHelpTopic.<init>(GenericCommandHelpTopic.java:50) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:135) ~[paper-1.19.2.jar:git-Paper-142]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:493) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-142]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by BillyGalbreath** [comment]
oh yikes. i'll get this fixed
