### ISSUE TITLE
java.lang.RuntimeException: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open

### ISSUE THREAD

**Issue by DexterSK** [BillyGalbreath/Pl3xMap#124]
[12:07:30 WARN]: java.lang.RuntimeException: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
[12:07:30 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:155)
[12:07:30 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateMarkerData.lambda$parseLayers$0(UpdateMarkerData.java:67)
[12:07:30 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
[12:07:30 WARN]:        at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
[12:07:30 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateMarkerData.parseLayers(UpdateMarkerData.java:49)
[12:07:30 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateMarkerData.run(UpdateMarkerData.java:40)
[12:07:30 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[12:07:30 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[12:07:30 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[12:07:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:07:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:07:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:07:30 WARN]: Caused by: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
[12:07:30 WARN]:        at java.base/sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
[12:07:30 WARN]:        at java.base/sun.nio.ch.FileDispatcherImpl.truncate(FileDispatcherImpl.java:90)
[12:07:30 WARN]:        at java.base/sun.nio.ch.FileChannelImpl.truncate(FileChannelImpl.java:437)
[12:07:30 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:150)
[12:07:30 WARN]:        ... 11 more
[12:07:30 WARN]: java.lang.RuntimeException: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
[12:07:30 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:155)
[12:07:30 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateMarkerData.parseLayers(UpdateMarkerData.java:75)
[12:07:30 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateMarkerData.run(UpdateMarkerData.java:40)
[12:07:30 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[12:07:30 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[12:07:30 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[12:07:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:07:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:07:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:07:30 WARN]: Caused by: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
[12:07:30 WARN]:        at java.base/sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
[12:07:30 WARN]:        at java.base/sun.nio.ch.FileDispatcherImpl.truncate(FileDispatcherImpl.java:90)
[12:07:30 WARN]:        at java.base/sun.nio.ch.FileChannelImpl.truncate(FileChannelImpl.java:437)
[12:07:30 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:150)
[12:07:30 WARN]:        ... 8 more
[12:07:31 WARN]: java.lang.RuntimeException: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
[12:07:31 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:155)
[12:07:31 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateSettingsData.lambda$parseWorlds$2(UpdateSettingsData.java:104)
[12:07:31 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
[12:07:31 WARN]:        at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
[12:07:31 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateSettingsData.parseWorlds(UpdateSettingsData.java:74)
[12:07:31 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateSettingsData.parseSettings(UpdateSettingsData.java:146)
[12:07:31 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateSettingsData.run(UpdateSettingsData.java:31)
[12:07:31 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[12:07:31 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[12:07:31 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[12:07:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:07:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:07:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:07:31 WARN]: Caused by: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
[12:07:31 WARN]:        at java.base/sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
[12:07:31 WARN]:        at java.base/sun.nio.ch.FileDispatcherImpl.truncate(FileDispatcherImpl.java:90)
[12:07:31 WARN]:        at java.base/sun.nio.ch.FileChannelImpl.truncate(FileChannelImpl.java:437)
[12:07:31 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:150)
[12:07:31 WARN]:        ... 12 more
[12:07:31 WARN]: java.lang.RuntimeException: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
[12:07:31 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:155)
[12:07:31 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateSettingsData.parseSettings(UpdateSettingsData.java:151)
[12:07:31 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateSettingsData.run(UpdateSettingsData.java:31)
[12:07:31 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[12:07:31 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[12:07:31 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[12:07:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:07:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:07:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:07:31 WARN]: Caused by: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
[12:07:31 WARN]:        at java.base/sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
[12:07:31 WARN]:        at java.base/sun.nio.ch.FileDispatcherImpl.truncate(FileDispatcherImpl.java:90)
[12:07:31 WARN]:        at java.base/sun.nio.ch.FileChannelImpl.truncate(FileChannelImpl.java:437)
[12:07:31 WARN]:        at Pl3xMap-1.19.2-314.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:150)
[12:07:31 WARN]:        ... 8 more

**Comment by dashtisser** [comment]
I have the same problem, how do i fix it.

**Comment by BillyGalbreath** [comment]
¯\_(ツ)_/¯

No one's explaining shit or giving me any info to work with other than this vague as fuck stacktrace.

**Comment by dashtisser** [comment]
This is only on windows 10, this bug is not present on Linux. it works but gives me the garbage in the console.

**Comment by purejosh** [comment]
I'm also getting this error on start up. It repeats itself every second. 
```
[10:06:02 WARN]: java.lang.RuntimeException: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
[10:06:02 WARN]: at Pl3xMap-1.19.2-314.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:155)
[10:06:02 WARN]: at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateSettingsData.parseSettings(UpdateSettingsData.java:151)
[10:06:02 WARN]: at Pl3xMap-1.19.2-314.jar//net.pl3x.map.task.UpdateSettingsData.run(UpdateSettingsData.java:31)
[10:06:02 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[10:06:02 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[10:06:02 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[10:06:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:06:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:06:02 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[10:06:02 WARN]: Caused by: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
[10:06:02 WARN]: at java.base/sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
[10:06:02 WARN]: at java.base/sun.nio.ch.FileDispatcherImpl.truncate(FileDispatcherImpl.java:90)
[10:06:02 WARN]: at java.base/sun.nio.ch.FileChannelImpl.truncate(FileChannelImpl.java:437)
[10:06:02 WARN]: at Pl3xMap-1.19.2-314.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:150)
[10:06:02 WARN]: ... 8 more
```

Here's the latest.log. 
[latest.log](https://github.com/BillyGalbreath/Pl3xMap/files/9912103/latest.log)

I am running this on a Windows host, for what it's worth. 

Any information you need to continue this investigation, I'm happy to provide. If you could reopen this github issue, that would be great.

**Comment by BillyGalbreath** [comment]
Yeah. Already aware it's a Windows filesystem issue. I'll add in some wonky workaround for that oddball OS once my IRL stuff settles and I have time to setup some VM with Windows to test on.

**Comment by BillyGalbreath** [comment]
Let me know if [build 315](https://modrinth.com/plugin/pl3xmap/version/1.19.2-315) fixes this issue.

**Comment by DexterSK** [comment]
[15:29:53 WARN]: java.lang.RuntimeException: java.io.FileNotFoundException: plugins\Pl3xMap\web\tiles\world\markers\spawn.json (The system cannot find the path specified)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:152)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.task.UpdateMarkerData.lambda$parseLayers$0(UpdateMarkerData.java:68)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
[15:29:53 WARN]:        at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.task.UpdateMarkerData.parseLayers(UpdateMarkerData.java:49)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.task.UpdateMarkerData.run(UpdateMarkerData.java:40)
[15:29:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[15:29:53 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:29:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:29:53 WARN]: Caused by: java.io.FileNotFoundException: plugins\Pl3xMap\web\tiles\world\markers\spawn.json (The system cannot find the path specified)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[15:29:53 WARN]:        at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:148)
[15:29:53 WARN]:        ... 11 more
[15:29:53 WARN]: java.lang.RuntimeException: java.io.FileNotFoundException: plugins\Pl3xMap\web\tiles\world\markers\players.json (The system cannot find the path specified)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:152)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.task.UpdateMarkerData.lambda$parseLayers$0(UpdateMarkerData.java:68)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
[15:29:53 WARN]:        at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.task.UpdateMarkerData.parseLayers(UpdateMarkerData.java:49)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.task.UpdateMarkerData.run(UpdateMarkerData.java:40)
[15:29:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[15:29:53 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:29:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:29:53 WARN]: Caused by: java.io.FileNotFoundException: plugins\Pl3xMap\web\tiles\world\markers\players.json (The system cannot find the path specified)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[15:29:53 WARN]:        at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:148)
[15:29:53 WARN]:        ... 11 more
[15:29:53 WARN]: java.lang.RuntimeException: java.io.FileNotFoundException: plugins\Pl3xMap\web\tiles\world\markers\worldborder.json (The system cannot find the path specified)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:152)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.task.UpdateMarkerData.lambda$parseLayers$0(UpdateMarkerData.java:68)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
[15:29:53 WARN]:        at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.task.UpdateMarkerData.parseLayers(UpdateMarkerData.java:49)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.task.UpdateMarkerData.run(UpdateMarkerData.java:40)
[15:29:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[15:29:53 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:29:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:29:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:29:53 WARN]: Caused by: java.io.FileNotFoundException: plugins\Pl3xMap\web\tiles\world\markers\worldborder.json (The system cannot find the path specified)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[15:29:53 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[15:29:53 WARN]:        at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
[15:29:53 WARN]:        at Pl3xMap-1.19.2-315.jar//net.pl3x.map.util.FileUtil.write(FileUtil.java:148)
[15:29:53 WARN]:        ... 11 more

**Comment by BillyGalbreath** [comment]
Have I mentioned how much I hate Windows?

Go ahead and give [build 316](https://modrinth.com/plugin/pl3xmap/version/1.19.2-316) a try. 

Also, @DexterSK use a paste service (like pastebin) when posting logs. They are really hard to read when they are just pasted on here as a comment.

**Comment by DexterSK** [comment]
@BillyGalbreath yep sorry for thah logs, maybe next time huh? xD
Anyway its working now, thanks!
