### ISSUE TITLE
SWM Support

### ISSUE THREAD

**Issue by ThePlay3r** [BillyGalbreath/Pl3xMap#138]
When trying to use Pl3xMap and [SWM](https://github.com/InfernalSuite/AdvancedSlimePaper) together, Pl3xMap spams console with "Player is in unloaded world" exceptions while being in a SWM world.

```
[18:59:01 WARN]: java.lang.IllegalStateException: Player is in an unloaded world!
[18:59:01 WARN]:        at Pl3xMap-1.19.3-320.jar//net.pl3x.map.player.BukkitPlayer.getWorld(BukkitPlayer.java:59)
[18:59:01 WARN]:        at Pl3xMap-1.19.3-320.jar//net.pl3x.map.task.UpdateSettingsData.lambda$parsePlayers$0(UpdateSettingsData.java:49)
[18:59:01 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
[18:59:01 WARN]:        at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
[18:59:01 WARN]:        at Pl3xMap-1.19.3-320.jar//net.pl3x.map.task.UpdateSettingsData.parsePlayers(UpdateSettingsData.java:39)
[18:59:01 WARN]:        at Pl3xMap-1.19.3-320.jar//net.pl3x.map.task.UpdateSettingsData.parseSettings(UpdateSettingsData.java:145)
[18:59:01 WARN]:        at Pl3xMap-1.19.3-320.jar//net.pl3x.map.task.UpdateSettingsData.run(UpdateSettingsData.java:31)
[18:59:01 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[18:59:01 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[18:59:01 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[18:59:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:59:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:59:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by BillyGalbreath** [comment]
See comments in #139
