### ISSUE TITLE
Again a message and crash

### ISSUE THREAD

**Issue by Otte-S** [BillyGalbreath/Pl3xMap#143]
[07:52:46 WARN]: java.nio.InvalidMarkException
[07:52:46 WARN]:        at java.base/java.nio.Buffer.reset(Buffer.java:422)
[07:52:46 WARN]:        at java.base/java.nio.ByteBuffer.reset(ByteBuffer.java:1555)
[07:52:46 WARN]:        at Pl3xMap-1.19.4-333.jar//net.pl3x.map.render.builtin.BlockInfoRenderer.saveData(BlockInfoRenderer.java:93)
[07:52:46 WARN]:        at Pl3xMap-1.19.4-333.jar//net.pl3x.map.render.ScanTask.lambda$scanRegion$3(ScanTask.java:122)
[07:52:46 WARN]:        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
[07:52:46 WARN]:        at Pl3xMap-1.19.4-333.jar//net.pl3x.map.render.ScanTask.lambda$scanRegion$4(ScanTask.java:122)
[07:52:46 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[07:52:46 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[07:52:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:52:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:52:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Otte-S** [comment]
And this message shows up...

[07:54:23 WARN]: java.lang.RuntimeException: java.io.EOFException: Unexpected end of ZLIB input stream
[07:54:23 WARN]:        at Pl3xMap-1.19.4-333.jar//net.pl3x.map.render.builtin.BlockInfoRenderer.allocateData(BlockInfoRenderer.java:50)
[07:54:23 WARN]:        at Pl3xMap-1.19.4-333.jar//net.pl3x.map.render.ScanTask.lambda$scanRegion$1(ScanTask.java:86)
[07:54:23 WARN]:        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
[07:54:23 WARN]:        at Pl3xMap-1.19.4-333.jar//net.pl3x.map.render.ScanTask.scanRegion(ScanTask.java:86)
[07:54:23 WARN]:        at Pl3xMap-1.19.4-333.jar//net.pl3x.map.render.ScanTask.run(ScanTask.java:75)
[07:54:23 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[07:54:23 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[07:54:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:54:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:54:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:54:23 WARN]: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[07:54:23 WARN]:        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
[07:54:23 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[07:54:23 WARN]:        at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[07:54:23 WARN]:        at java.base/java.io.InputStream.readNBytes(InputStream.java:409)
[07:54:23 WARN]:        at java.base/java.io.InputStream.readAllBytes(InputStream.java:346)
[07:54:23 WARN]:        at Pl3xMap-1.19.4-333.jar//net.pl3x.map.util.FileUtil.readGzip(FileUtil.java:183)
[07:54:23 WARN]:        at Pl3xMap-1.19.4-333.jar//net.pl3x.map.render.builtin.BlockInfoRenderer.allocateData(BlockInfoRenderer.java:47)
[07:54:23 WARN]:        ... 9 more

**Comment by granny** [comment]
You're still on build #333. You're over 4 builds behind.
