### ISSUE TITLE
Again.. Strange message after updating to 337

### ISSUE THREAD

**Issue by Otte-S** [BillyGalbreath/Pl3xMap#144]
After updating i am getting this message while rendering

[09:53:21 WARN]: [Pl3xMap​] Could not read tile image: plugins/Pl3xMap/web/tiles/Survival/3/biomes/0_0.png
[09:53:21 WARN]: javax.imageio.IIOException: Error skipping PNG metadata
[09:53:21 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:752)
[09:53:21 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1416)
[09:53:21 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1847)
[09:53:21 WARN]:        at java.desktop/javax.imageio.ImageReader.read(ImageReader.java:938)
[09:53:21 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.image.io.Png.read(Png.java:30)
[09:53:21 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.image.Image.getBuffer(Image.java:94)
[09:53:21 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.image.Image.saveToDisk(Image.java:78)
[09:53:21 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.image.Image$Holder.save(Image.java:163)
[09:53:21 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.render.Renderer.saveData(Renderer.java:73)
[09:53:21 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.render.ScanTask.lambda$scanRegion$3(ScanTask.java:122)
[09:53:21 WARN]:        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
[09:53:21 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.render.ScanTask.lambda$scanRegion$4(ScanTask.java:122)
[09:53:21 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[09:53:21 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[09:53:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:53:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:53:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[09:53:21 WARN]: Caused by: java.io.EOFException
[09:53:21 WARN]:        at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readInt(ImageInputStreamImpl.java:251)
[09:53:21 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:723)
[09:53:21 WARN]:        ... 16 more

**Comment by Otte-S** [comment]
And this....


[09:55:22 WARN]: java.lang.RuntimeException: java.io.EOFException: Unexpected end of ZLIB input stream
[09:55:22 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.render.builtin.BlockInfoRenderer.allocateData(BlockInfoRenderer.java:50)
[09:55:22 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.render.ScanTask.lambda$scanRegion$1(ScanTask.java:86)
[09:55:22 WARN]:        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
[09:55:22 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.render.ScanTask.scanRegion(ScanTask.java:86)
[09:55:22 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.render.ScanTask.run(ScanTask.java:75)
[09:55:22 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[09:55:22 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[09:55:22 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:55:22 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:55:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[09:55:22 WARN]: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[09:55:22 WARN]:        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
[09:55:22 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[09:55:22 WARN]:        at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[09:55:22 WARN]:        at java.base/java.io.InputStream.readNBytes(InputStream.java:409)
[09:55:22 WARN]:        at java.base/java.io.InputStream.readAllBytes(InputStream.java:346)
[09:55:22 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.util.FileUtil.readGzip(FileUtil.java:183)
[09:55:22 WARN]:        at Pl3xMap-1.19.4-337.jar//net.pl3x.map.render.builtin.BlockInfoRenderer.allocateData(BlockInfoRenderer.java:47)
[09:55:22 WARN]:        ... 9 more
