### ISSUE TITLE
Pl3xMap 1.19.4-418 crashes when used on server via fabric

### ISSUE THREAD

**Issue by Garmelon** [BillyGalbreath/Pl3xMap#152]
Hello, I'm trying to use [the latest Pl3xMap](https://modrinth.com/plugin/pl3xmap/version/1.19.4-418) on my server via Fabric. 

However, it crashes a few seconds after the `Preparing level "world"` message is logged. This happens whenever I try to start the server, including the first time after installing the Pl3xMap jar.

The `config/pl3xmap` directory was created before the crash. I did not change any settings and did not spot any settings that looked wrong.

A `config/pl3xmap/markers/minecraft:overworld` directory was created and is empty.

[The crash report](https://github.com/BillyGalbreath/Pl3xMap/files/11507846/crash-2023-05-18_12.33.11-server.txt)

**Comment by BillyGalbreath** [comment]
Can you send me your latest.log that shows what happened right before this crash report?

**Comment by Garmelon** [comment]
Sure, [latest.log](https://github.com/BillyGalbreath/Pl3xMap/files/11507914/latest.log)

**Comment by Garmelon** [comment]
To clarify: This is the first time I'm trying to use Pl3xMap on my server. I realized the initial description could be interpreted as meaning that something broke recently. I could try older versions if that helps.

**Comment by BillyGalbreath** [comment]
Ok, I found quite a bit of issues. Give build 420 a try

**Comment by Garmelon** [comment]
Thanks, build 420 successfully renders and serves a map. :)

I noticed an exception while running `pl3xmap show` with no further arguments from the server command line, but that doesn't seem to interfere with pl3xmap working.
```
pl3xmap show
[14:35:12] [Server thread/INFO]: [Pl3xMap] You must specify the player
[14:35:12] [Server thread/INFO]: [STDERR]: net.pl3x.map.core.command.exception.PlayerParseException: You must specify the player
[14:35:12] [Server thread/INFO]: [STDERR]: 	at net.pl3x.map.core.command.argument.PlayerArgument.resolve(PlayerArgument.java:117)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at net.pl3x.map.core.command.commands.ShowCommand.execute(ShowCommand.java:57)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at cloud.commandframework.CommandManager.executeCommand(CommandManager.java:189)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at cloud.commandframework.fabric.FabricExecutor.run(FabricExecutor.java:82)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:285)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_44252(class_2170.java:278)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3176.method_13941(class_3176.java:299)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3176.method_3813(class_3176.java:284)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
[14:35:12] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Garmelon** [comment]
Oh, I'm also now noticing a *lot* of these exceptions appearing. I triggered a fullrender for `minecraft:overworld` manually, maybe that has something to do with this?

Not sure if it's worth reopening the issue since I *can* see the map in my browser, but something's definitely wrong here.

```
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: java.io.EOFException
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.io.RandomAccessFile.readByte(RandomAccessFile.java:708)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.world.Region.loadChunk(Region.java:117)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.world.Region.getChunk(Region.java:88)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.Renderer.scanData(Renderer.java:103)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.task.RegionScanTask.scanRegion(RegionScanTask.java:119)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.task.RegionScanTask.run(RegionScanTask.java:89)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: java.io.EOFException
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.io.RandomAccessFile.readByte(RandomAccessFile.java:708)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.world.Region.loadChunk(Region.java:117)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.world.Region.getChunk(Region.java:88)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.Renderer.scanData(Renderer.java:103)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.task.RegionScanTask.scanRegion(RegionScanTask.java:119)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.task.RegionScanTask.run(RegionScanTask.java:89)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: java.io.EOFException
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.io.RandomAccessFile.readByte(RandomAccessFile.java:708)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.world.Region.loadChunk(Region.java:117)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.world.Region.getChunk(Region.java:88)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.Renderer.scanData(Renderer.java:103)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.task.RegionScanTask.scanRegion(RegionScanTask.java:119)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.task.RegionScanTask.run(RegionScanTask.java:89)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[14:38:35] [Pl3xMap-Renderer-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by BillyGalbreath** [comment]
You can ignore those EOF exceptions. That's just Java being extra verbose. I'll silence that in build 421 ^_^

**Comment by Garmelon** [comment]
The console is nice and quiet on 421, yay
