### ISSUE TITLE
Plugin stops during server startup

### ISSUE THREAD

**Issue by BorealBlizzard** [BillyGalbreath/Pl3xMap#159]
Here is a copy of my server log of the issue area after i turned on debug mode in the config:
```
[Pl3xMap]: Enabling Pl3xMap v1.19.4-435

Console
07:45:00

at libs.org.simpleyaml.configuration.implementation.snakeyaml.lib.composer.Composer.composeNode(Composer.java:212) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.snakeyaml.lib.composer.Composer.composeValueNode(Composer.java:357) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.snakeyaml.lib.composer.Composer.composeMappingChildren(Composer.java:336) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.snakeyaml.lib.composer.Composer.composeMappingNode(Composer.java:311) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.snakeyaml.lib.composer.Composer.composeNode(Composer.java:212) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.snakeyaml.lib.composer.Composer.getNode(Composer.java:134) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.snakeyaml.lib.composer.Composer.getSingleNode(Composer.java:160) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.snakeyaml.lib.constructor.BaseConstructor.getSingleData(BaseConstructor.java:184) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.snakeyaml.lib.Yaml.loadFromReader(Yaml.java:477) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.snakeyaml.lib.Yaml.load(Yaml.java:430) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.SimpleYamlImplementation.load(SimpleYamlImplementation.java:72) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.implementation.SimpleYamlImplementation.load(SimpleYamlImplementation.java:57) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.file.YamlConfiguration.load(YamlConfiguration.java:134) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.file.YamlFile.load(YamlFile.java:579) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.file.YamlConfiguration.load(YamlConfiguration.java:272) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.file.YamlConfiguration.load(YamlConfiguration.java:199) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.file.YamlFile.load(YamlFile.java:542) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.file.YamlFile.loadWithComments(YamlFile.java:560) ~[Pl3xMap-1.19.4-435.jar:?]
at libs.org.simpleyaml.configuration.file.YamlFile.createOrLoadWithComments(YamlFile.java:615) ~[Pl3xMap-1.19.4-435.jar:?]
at net.pl3x.map.core.configuration.AbstractConfig.reload(AbstractConfig.java:55) ~[Pl3xMap-1.19.4-435.jar:?]
... 16 more

INFO
07:45:00

[Pl3xMap]: Disabling Pl3xMap v1.19.4-435
[Pl3xMap]: [DEBUG] Stopping tasks
[Pl3xMap]: [DEBUG] Stopping internal server
[Pl3xMap]: [WARN] An error occurred with the internal webserver
[Pl3xMap]: [DEBUG] Unregistering players
[Pl3xMap]: [DEBUG] Unregistering worlds
[Pl3xMap]: [DEBUG] Unregistering renderers
[Pl3xMap]: [DEBUG] Unregistering icons
[Pl3xMap]: [DEBUG] Unregistering heightmaps
[Pl3xMap]: [DEBUG] Unregistering tile image types
```
Only settings changed in the config is the web-address and port

**Comment by BillyGalbreath** [comment]
Post your configs and _full_ logs.

**Comment by BillyGalbreath** [comment]
It's saying that you broke your colors.yml file

**Comment by BillyGalbreath** [comment]
I hope you found what you broke in colors.yml and was able to fix it ^_^
