### ISSUE TITLE
Issues with startup

### ISSUE THREAD

**Issue by IrKaos** [BillyGalbreath/Pl3xMap#161]
Server is extremely slow to start due to Pl3xMap. I tried deleting the folder and restarting I have also updated to build 440 with no luck. 
Below is a small snippet of the error. It runs through Retried waiting for GClocker for several minutes.

`[14:28:57] [Pl3xMap-Renderer-3/INFO]: [Pl[62.371s][warning][gc,alloc] Pl3xMap-Renderer-2: Retried waiting for GCLocker too often allocating 131074 words
3xMap] [WARN] Could not read tile image: plugins\Pl3xMap\web\tiles\world\2\flowermap\-1_-1.png
[14:28:57] [Pl3xMap-Renderer-3/WARN]: javax.imageio.IIOException: Caught exception during read:
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1854)
                              Pl3xMap-Renderer-2: Retried waiting for GCLocker too often allocating 131074 words
[62.374s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131074 words
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at java.desktop/javax.imageio.ImageReader.read(ImageReader.java:938)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at net.pl3x.map.core.image.io.IO$Type.read(IO.java:99)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at net.pl3x.map.core.image.TileImage.getBuffer(TileImage.java:122)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at net.pl3x.map.core.image.TileImage.saveToDisk(TileImage.java:102)
          [warning][gc,alloc] Pl3xMap-Renderer-2: Retried waiting for GCLocker too often allocating 131074 words
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at net.pl3x.map.core.renderer.Renderer.saveData(Renderer.java:87)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at net.pl3x.map.core.renderer.task.RegionScanTask.saveImages(RegionScanTask.java:127)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at net.pl3x.map.core.renderer.task.RegionScanTask.run(RegionScanTask.java:93)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
 Pl3xMap-Renderer-2: Retried waiting for GCLocker too often allocating 131074 words
[14:28:57] [Pl3xMap-Renderer-3/WARN]:   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[14:28:57] [Pl3xMap-Renderer-3/WARN]: Caused by: java.lang.OutOfMemoryError: Java heap space
[14:28:57] [Pl3xMap-Renderer-2/WARN]: java.lang.OutOfMemoryError: Java heap space
[14:28:57] [Pl3xMap-Renderer-2/WARN]: java.lang.OutOfMemoryError: Java heap space
[14:28:57] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
[14:28:57] [Pl3xMap-Renderer-2/WARN]: java.lang.OutOfMemoryError: Java heap space
[14:28:57] [Pl3xMap-Renderer-2/WARN]: java.lang.OutOfMemoryError: Java heap space
>[62.679s][warning][gc,alloc] Pl3xMap-Renderer-4: Retried waiting for GCLocker too often allocating 131074 words
[14:28:57] [Pl3xMap-Renderer-4/WARN]: java.lang.OutOfMemoryError: Java heap space
>[65.507s][warning][gc,alloc] XNIO-1 I/O-9: Retried waiting for GCLocker too often allocating 5313 words
[69.947s][warning][gc,alloc] XNIO-1 task-5: Retried waiting for GCLocker too often allocating 256 words
[69.949s][warning][gc,alloc] TerminalConsoleWriter: Retried waiting for GCLocker too often allocating 256 words
[14:29:04] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 7166ms or 143 ticks behind
>[69.970s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131076 words
[14:29:04] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
>[70.292s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131076 words
[14:29:05] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
>[70.593s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131076 words
[14:29:05] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
>[70.887s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131076 words
[14:29:05] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
>[70.892s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131074 words
[14:29:05] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
>[71.188s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131074 words
[14:29:06] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
>[71.193s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131074 words
[14:29:06] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
>[71.200s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131074 words
[14:29:06] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
>[71.204s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131074 words
[14:29:06] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
[14:29:07] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
>[73.181s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 63934 words
[73.186s][warning][gc,alloc] Pl3xMap-Renderer-5: Retried waiting for GCLocker too often allocating 10259 words
[73.464s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 63934 words
[74.446s][warning][gc,alloc] Pl3xMap-Renderer-2: Retried waiting for GCLocker too often allocating 65536 words
[80.031s][warning][gc,alloc] Pl3xMap-Renderer-2: Retried waiting for GCLocker too often allocating 65536 words
[80.303s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 63933 words
[82.547s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 63930 words
[84.453s][warning][gc,alloc] Pl3xMap-Renderer-2: Retried waiting for GCLocker too often allocating 65536 words
[84.453s][warning][gc,alloc] pool-26-thread-1: Retried waiting for GCLocker too often allocating 256 words
[85.813s][warning][gc,alloc] Pl3xMap-Renderer-0: Retried waiting for GCLocker too often allocating 65536 words
[87.697s][warning][gc,alloc] Pl3xMap-Renderer-0: Retried waiting for GCLocker too often allocating 65536 words
[91.825s][warning][gc,alloc] Netty Server IO #0: Retried waiting for GCLocker too often allocating 256 words
[91.825s][warning][gc,alloc] MVStore background writer nio:D:/Spigot Server/Server/plugins/BanManager/local_bans.mv.db: Retried waiting for GCLocker too often allocating 335 words
[91.825s][warning][gc,alloc] XNIO-1 task-3: Retried waiting for GCLocker too often allocating 331 words
[94.272s][warning][gc,alloc] XNIO-1 task-5: Retried waiting for GCLocker too often allocating 331 words
[120.099s][warning][gc,alloc] XNIO-1 task-5: Retried waiting for GCLocker too often allocating 333 words
[120.642s][warning][gc,alloc] XNIO-1 task-6: Retried waiting for GCLocker too often allocating 1067 words
[129.877s][warning][gc,alloc] Netty Server IO #0: Retried waiting for GCLocker too often allocating 12758 words
[154.657s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 64620 words
[14:30:31] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[158.268s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[14:30:33] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[161.331s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131076 words
[14:30:36] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[164.875s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131076 words
[14:30:40] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
[14:30:43] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[169.473s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[14:30:44] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[169.485s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[14:30:44] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[169.503s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[14:30:44] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[169.798s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[169.802s][warning][gc,alloc] Server thread: Retried waiting for GCLocker too often allocating 256 words
[14:30:44] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[169.818s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[14:30:45] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[170.104s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[14:30:45] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[170.115s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[170.135s][warning][gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131076 words
[14:30:45] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
[170.409s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[warning][14:30:45] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
[gc,alloc] Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131074 words
[14:30:45] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
                               Pl3xMap-Renderer-3: Retried waiting for GCLocker too often allocating 131074 words
[14:30:45] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
[170.418s]>[warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[14:30:45] [Pl3xMap-Renderer-3/WARN]: java.lang.OutOfMemoryError: Java heap space
[14:30:45] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[170.717s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[14:30:45] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[172.675s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[172.949s][warning][gc,alloc] Pl3xMap-Renderer-0: Retried waiting for GCLocker too often allocating 65536 words
[174.840s][warning][gc,alloc] XNIO-1 task-5: Retried waiting for GCLocker too often allocating 256 words
[14:30:48] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
>[175.386s][warning][gc,alloc] Pl3xMap-Renderer-1: Retried waiting for GCLocker too often allocating 131074 words
[14:30:52] [Pl3xMap-Renderer-1/WARN]: java.lang.OutOfMemoryError: Java heap space`

**Comment by BillyGalbreath** [comment]
This is not a bug. Please join the Discord server for basic support requests.
