### ISSUE TITLE
Error with custom web location

### ISSUE THREAD

**Issue by Hundr** [BillyGalbreath/Pl3xMap#168]
Using latest Spigot server on a Linux distro. with a custom location for the internal web server, I keep getting these kinds of error messages for files in that directory (markers). The directory has full read/write permission for everyone as well. Otherwise the plugin is running okay from what I can tell.

[XNIO-1 task-4/WARN]: java.nio.file.NoSuchFileException: /path_to_custom_location/web/tiles/HarMine3/markers/pl3xmap_players.json
[XNIO-1 task-4/WARN]:        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[XNIO-1 task-4/WARN]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[XNIO-1 task-4/WARN]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[XNIO-1 task-4/WARN]:        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[XNIO-1 task-4/WARN]:        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
[XNIO-1 task-4/WARN]:        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[XNIO-1 task-4/WARN]:        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
[XNIO-1 task-4/WARN]:        at net.pl3x.map.core.httpd.HttpdServer.lambda$startServer$0(HttpdServer.java:59)
[XNIO-1 task-4/WARN]:        at libs.io.undertow.server.handlers.resource.PathResourceManager.getFileResource(PathResourceManager.java:416)
[XNIO-1 task-4/WARN]:        at libs.io.undertow.server.handlers.resource.PathResourceManager.getResource(PathResourceManager.java:240)
[XNIO-1 task-4/WARN]:        at libs.io.undertow.server.handlers.resource.DefaultResourceSupplier.getResource(DefaultResourceSupplier.java:39)
[XNIO-1 task-4/WARN]:        at libs.io.undertow.server.handlers.resource.ResourceHandler$1.handleRequest(ResourceHandler.java:205)
[XNIO-1 task-4/WARN]:        at libs.io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
[XNIO-1 task-4/WARN]:        at libs.io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
[XNIO-1 task-4/WARN]:        at libs.org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[XNIO-1 task-4/WARN]:        at libs.org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[XNIO-1 task-4/WARN]:        at libs.org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[XNIO-1 task-4/WARN]:        at libs.org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
[XNIO-1 task-4/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by BillyGalbreath** [comment]
Can you provide the actual log output and your config file?

**Comment by Hundr** [comment]
This is from a restart
[latest.log](https://github.com/BillyGalbreath/Pl3xMap/files/11839917/latest.log)

**Comment by BillyGalbreath** [comment]
That log doesn't show what you are reporting, but it does show a different bug that I've just fixed in build 450.

**Comment by Hundr** [comment]
[config_copy.txt](https://github.com/BillyGalbreath/Pl3xMap/files/11839947/config_copy.txt)

**Comment by Hundr** [comment]
[2023-06-22-1.log](https://github.com/BillyGalbreath/Pl3xMap/files/11839981/2023-06-22-1.log)

**Comment by Hundr** [comment]
[2023-06-21-1.log](https://github.com/BillyGalbreath/Pl3xMap/files/11839996/2023-06-21-1.log)

**Comment by Hundr** [comment]
[2023-06-20-1.log](https://github.com/BillyGalbreath/Pl3xMap/files/11840020/2023-06-20-1.log)

**Comment by BillyGalbreath** [comment]
Give build 450 a try

**Comment by Hundr** [comment]
Hope those help better

**Comment by Hundr** [comment]
> Give build 450 a try

I do not see that build on modrinth yet

**Comment by Hundr** [comment]
450 seems to have fixed the WARN file error. Thank you. Still getting the other error though when starting.
[latest.log](https://github.com/BillyGalbreath/Pl3xMap/files/11840243/latest.log)

**Comment by BillyGalbreath** [comment]
Ok, the last error is with Pl3xMap-Signs. I went ahead and tested all the addons to make sure they work with Spigot. I fixed both the Signs and Banners addons, so update the ones you use to get rid of those last errors

**Comment by Hundr** [comment]
Awesome! Thank you for your help, its very much appreciated.
